name: Code Lint
on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  lint:
    name: Biome
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Download deps
        run: pnpm install --frozen-lockfile

      - name: Check and Lint
        run: pnpm run validate